### ISSUE TITLE
Fixes for DB Normalization article

### ISSUE THREAD

**Issue by KiraUmea** [edu-python-course/edu-python-course.github.io#43]
https://edu-python-course.github.io/_build/html/ua/rdbms/normalization.html

Важко читається строка: 
"Щоб перенести її в 2NF, спеціальну таблицю для зберігання інформації про самі товари має бути створено." 

Якщо я правильно розумію, її можна замінити на: 
"Щоб перенести її в 2NF, треба створити спеціальну таблицю для зберігання інформації про самі товари".

**Comment by shorodilov** [comment]
https://github.com/edu-python-course/edu-python-course.github.io/blob/3805f7b5fb11630715a575c472e5a1b22da87ba6/src/_locales/ua/LC_MESSAGES/rdbms.po#L714
