### ISSUE TITLE
Data hiding descriptions is unclear

### ISSUE THREAD

**Issue by MykolaShv** [edu-python-course/edu-python-course.github.io#44]
ось тут я у вашій лекції не побачив різниці між 1 та двома підкресленням:
Приховання Даних
Багато мов програмування мають реалізовані модифікатори доступу. Python також має, але насправді ні. Він реалізований на рівні конвенції. Усі члени класу, які починаються з підкреслення, вважаються захищеними членами та **не повинні бути доступними за межами екземпляр класу**; з іншого боку, члени, які починаються з двох символів підкреслення, вважаються приватними членами та **не повинні бути доступними за межами екземпляра класу.**
ПОСИЛАННЯ
https://edu-python-course.github.io/_build/html/ua/oop/intro.html#data-hiding

**Comment by shorodilov** [comment]
Reference to source file

https://github.com/edu-python-course/edu-python-course.github.io/blob/8e20669eba61e5e84929f2fbbde279fa02d6b78c/src/oop/intro.txt#L238
