### ISSUE TITLE
Content/translation enhancements for convenience store challenge

### ISSUE THREAD

**Issue by MykolaShv** [edu-python-course/edu-python-course.github.io#48]
загальна ціна.... згідно означення ЦІНА ЦЕ ГРОШОВИЙ ВИРАЗ ВАРТОСТІ ОДИНИЦІ ТОВАРУ.... я би змінив  **загальна сума вказаної кількості товару**, наприклад

ось тут
https://edu-python-course.github.io/_build/html/ua/appx/conv_store.html#conv_store.Product

**Comment by shorodilov** [comment]
Moved to "backlog"

**Comment by shorodilov** [comment]
https://github.com/edu-python-course/edu-python-course.github.io/blob/8e20669eba61e5e84929f2fbbde279fa02d6b78c/src/_locales/ua/LC_MESSAGES/appx.po#L700
